name: test
on:
  - push
env:
  CI: "true"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: apt install
        run: |
          sudo apt update
      - name: bundle install
        run: |
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake test
